name: go_router_extension
description: This is an extension package that makes it easier to use the go_router package
version: 0.0.5
homepage: https://github.com/betrider/go_router_extension.git
repository: https://github.com/betrider/go_router_extension.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: betrider.go_router_extension
        pluginClass: GoRouterExtensionPlugin
      ios:
        pluginClass: GoRouterExtensionPlugin
